# Generated by Django 5.0.4 on 2024-05-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto_profilo',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
