# Generated by Django 5.0.4 on 2024-05-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_foto_profilo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='foto_profilo',
        ),
        migrations.AddField(
            model_name='profile',
            name='fotoprofilo',
            field=models.ImageField(default='profile_default.png', upload_to=''),
        ),
    ]
