# Generated by Django 5.0.4 on 2024-05-21 06:52

import django.db.models.deletion
import django.utils.timezone
import prestiti.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libreria', '0015_alter_libro_disponibile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inzio', models.DateField(default=django.utils.timezone.now)),
                ('data_fine', models.DateField(default=prestiti.models.durata_prestito)),
                ('stato', models.CharField(choices=[('richiesta', 'Richiesta'), ('in corso', 'In corso'), ('riconsegna', 'Riconsegna'), ('chiuso', 'Chiuso')], max_length=20)),
                ('libro', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='libreria.libro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
