# Generated by Django 5.0.4 on 2024-05-14 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_autore_libroautore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casa_editrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nazionalita', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='libro',
            name='author',
        ),
        migrations.AddField(
            model_name='libro',
            name='autori',
            field=models.ManyToManyField(through='libreria.LibroAutore', to='libreria.autore'),
        ),
        migrations.AddField(
            model_name='libro',
            name='casa_editrice',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='libreria.casa_editrice'),
        ),
    ]
