# Generated by Django 5.0.4 on 2024-05-14 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_casa_editrice_remove_libro_author_libro_autori_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='casa_editrice',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='libreria.casa_editrice'),
        ),
    ]
