# Generated by Django 5.0.4 on 2024-05-14 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_alter_libro_casa_editrice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='data_publication',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
