# Generated by Django 5.0.4 on 2024-05-14 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_alter_libro_data_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='data_publication',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
