# Generated by Django 5.0.4 on 2024-05-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0006_alter_libro_data_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='copertina',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
