# Generated by Django 5.0.4 on 2024-05-15 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0009_lingua_libro_lingua'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='lingua',
        ),
        migrations.DeleteModel(
            name='Lingua',
        ),
    ]
