# Generated by Django 5.0.4 on 2024-05-15 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0010_remove_libro_lingua_delete_lingua'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lingua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='lingua',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='libreria.lingua'),
        ),
    ]
