# Generated by Django 5.0.4 on 2024-05-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0011_lingua_libro_lingua'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='isbn',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
