# Generated by Django 5.0.4 on 2024-05-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0014_tag_librotag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='disponibile',
            field=models.BooleanField(default=True),
        ),
    ]
